require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe InformativeTextDailyBulletinsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # InformativeTextDailyBulletin. As you add validations to InformativeTextDailyBulletin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InformativeTextDailyBulletinsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all informative_text_daily_bulletins as @informative_text_daily_bulletins" do
      informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:informative_text_daily_bulletins)).to eq([informative_text_daily_bulletin])
    end
  end

  describe "GET #show" do
    it "assigns the requested informative_text_daily_bulletin as @informative_text_daily_bulletin" do
      informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
      get :show, {:id => informative_text_daily_bulletin.to_param}, valid_session
      expect(assigns(:informative_text_daily_bulletin)).to eq(informative_text_daily_bulletin)
    end
  end

  describe "GET #new" do
    it "assigns a new informative_text_daily_bulletin as @informative_text_daily_bulletin" do
      get :new, {}, valid_session
      expect(assigns(:informative_text_daily_bulletin)).to be_a_new(InformativeTextDailyBulletin)
    end
  end

  describe "GET #edit" do
    it "assigns the requested informative_text_daily_bulletin as @informative_text_daily_bulletin" do
      informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
      get :edit, {:id => informative_text_daily_bulletin.to_param}, valid_session
      expect(assigns(:informative_text_daily_bulletin)).to eq(informative_text_daily_bulletin)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new InformativeTextDailyBulletin" do
        expect {
          post :create, {:informative_text_daily_bulletin => valid_attributes}, valid_session
        }.to change(InformativeTextDailyBulletin, :count).by(1)
      end

      it "assigns a newly created informative_text_daily_bulletin as @informative_text_daily_bulletin" do
        post :create, {:informative_text_daily_bulletin => valid_attributes}, valid_session
        expect(assigns(:informative_text_daily_bulletin)).to be_a(InformativeTextDailyBulletin)
        expect(assigns(:informative_text_daily_bulletin)).to be_persisted
      end

      it "redirects to the created informative_text_daily_bulletin" do
        post :create, {:informative_text_daily_bulletin => valid_attributes}, valid_session
        expect(response).to redirect_to(InformativeTextDailyBulletin.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved informative_text_daily_bulletin as @informative_text_daily_bulletin" do
        post :create, {:informative_text_daily_bulletin => invalid_attributes}, valid_session
        expect(assigns(:informative_text_daily_bulletin)).to be_a_new(InformativeTextDailyBulletin)
      end

      it "re-renders the 'new' template" do
        post :create, {:informative_text_daily_bulletin => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested informative_text_daily_bulletin" do
        informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
        put :update, {:id => informative_text_daily_bulletin.to_param, :informative_text_daily_bulletin => new_attributes}, valid_session
        informative_text_daily_bulletin.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested informative_text_daily_bulletin as @informative_text_daily_bulletin" do
        informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
        put :update, {:id => informative_text_daily_bulletin.to_param, :informative_text_daily_bulletin => valid_attributes}, valid_session
        expect(assigns(:informative_text_daily_bulletin)).to eq(informative_text_daily_bulletin)
      end

      it "redirects to the informative_text_daily_bulletin" do
        informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
        put :update, {:id => informative_text_daily_bulletin.to_param, :informative_text_daily_bulletin => valid_attributes}, valid_session
        expect(response).to redirect_to(informative_text_daily_bulletin)
      end
    end

    context "with invalid params" do
      it "assigns the informative_text_daily_bulletin as @informative_text_daily_bulletin" do
        informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
        put :update, {:id => informative_text_daily_bulletin.to_param, :informative_text_daily_bulletin => invalid_attributes}, valid_session
        expect(assigns(:informative_text_daily_bulletin)).to eq(informative_text_daily_bulletin)
      end

      it "re-renders the 'edit' template" do
        informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
        put :update, {:id => informative_text_daily_bulletin.to_param, :informative_text_daily_bulletin => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested informative_text_daily_bulletin" do
      informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
      expect {
        delete :destroy, {:id => informative_text_daily_bulletin.to_param}, valid_session
      }.to change(InformativeTextDailyBulletin, :count).by(-1)
    end

    it "redirects to the informative_text_daily_bulletins list" do
      informative_text_daily_bulletin = InformativeTextDailyBulletin.create! valid_attributes
      delete :destroy, {:id => informative_text_daily_bulletin.to_param}, valid_session
      expect(response).to redirect_to(informative_text_daily_bulletins_url)
    end
  end

end
