development:
  adapter: postgresql
  encoding: utf8
  #database: dbcrpoftec
  #host: dbcrpoftec.conf6vxfcs4e.us-west-2.rds.amazonaws.com
  pool: 5
  #username: CRPOFTEC
  #password: crpo2016#ftec

  # conxão Local
<<<<<<< HEAD
  database: crpoLocal
  username: 
  password: 
=======

  # host: localhost
  # database: crpoLocal
  # username: postgres
  # password: gokussj9
  #host: localhost
  #database: crpoLocal
  #username: postgres
  #password: postgres
>>>>>>> 425a4ca60fd74f5e5ef51f8258af239cbcbfb4e7

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
