development:
  adapter: postgresql
  encoding: utf8
 database: dbcrpoftec
  host: dbcrpoftec.conf6vxfcs4e.us-west-2.rds.amazonaws.com
  pool: 5
  username: ad
  password: admin123

  # conxão Local
<<<<<<< HEAD

  # host: localhost
  # database: crpoLocal
  # username: postgres
  # password: gokussj9
=======
  #host: localhost
  #database: crpoLocal
  #username: postgres
  #password: postgres
>>>>>>> de1060bd5964ab08de15d07d81235b71e5fccdf6

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
