# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8ec71b35260b36342bb134fc5114367f1da6f8a154f3d5fed091d2edaff6ec2953db5f754238053ef5fc839726d907d387ad1a4600efb0d23451b1336d90470

test:
  secret_key_base: ed64d454393e5d798ff2f7044b83e99191e4731c0e6dfb23c03eeb00de061ac1b28fd8af3490a08642c036c9c98ee8fcb3132b0262a4b94c19de20ce0738c6a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
